id: P005612
initial_creation_type: ocr
source_metadata:
  id: bdr:W23618
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་འདོན་ཆ། ༼རྡོ་གྲུབ་དགོན་གྱི་ལུགས།༽
  author: ''
  volumes:
    f42312b7625343f2ad5ca3713f7e4b88:
      image_group_id: I1KG8582
      title: ''
      volume_number: 1
      total_pages: 1425
