id: I5C9488B9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T16:12:39+00:00'
last_modified: '2022-06-08T05:17:25.130734+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23618
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་འདོན་ཆ། ༼རྡོ་གྲུབ་དགོན་གྱི་ལུགས།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    03DE:
      image_group_id: I1KG8582
      title: ''
      total_pages: 1425
      order: 1
      base_file: 03DE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
